# Make sure to check the documentation at https://goreleaser.com
version: 2

env:
  - GIT_URL=https://github.com/huhu415/huhu
  - TZ=Asia/Shanghai
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X github.com/huhu415/mcp-memos/routes.Version={{.Version}}
      - -X github.com/huhu415/mcp-memos/routes.BuildDate={{.Date}}
      - -X github.com/huhu415/mcp-memos/routes.GitCommit={{.Commit}}

archives:
  - formats: [tar.gz]
    wrap_in_directory: true
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md

checksum:
  disable: true

# https://goreleaser.com/customization/changelog/
changelog:
  disable: true

# https://goreleaser.com/customization/release
release:
  # header:

  # footer: |
